repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.9.0
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ] # Ignore jupyter
      args: [ --fix ] # Fixes only safe issues.
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ] # Ignore jupyter