name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: |
          uv sync --all-extras --dev

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github .